# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 20:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacion',
            name='servicio_domestico',
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='aplica_art_310',
            field=models.BooleanField(default=True, verbose_name='Aplica el art. 310 CST?'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='avance_del_contrato',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='dias_semanales',
            field=models.DecimalField(decimal_places=0, default=7, max_digits=14),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='fecha_finalizacion',
            field=models.DateField(default=datetime.date(2017, 1, 25)),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2016, 1, 25)),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='fecha_liquidacion',
            field=models.DateField(default=datetime.date(2017, 1, 25)),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='tipo_salario',
            field=models.CharField(choices=[('confianza', 'Empleado De Confianza (sin h. extras)'), ('normal', 'Contrato Normal'), ('integral', 'Salario Integral (superior a 10 minimos)'), ('construccion', 'Construccion (por jornal durante una obra)'), ('domestico', 'Empleado Domestico (por jornal varios dias a la semana)')], default='normal', max_length=30),
        ),
    ]
