# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0002_auto_20170125_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='tipo_salario',
            field=models.CharField(choices=[('confianza', 'Empleado De Confianza (sin h. extras)'), ('normal', 'Salario Normal'), ('integral', 'Salario Integral (superior a 10 minimos)'), ('construccion', 'Construccion (por jornal durante una obra)'), ('domestico', 'Empleado Domestico (por jornal varios dias a la semana)')], default='normal', max_length=30),
        ),
    ]
