# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 03:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0003_auto_20170125_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacion',
            name='cuota_libranzas',
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='aplica_art_310',
            field=models.BooleanField(default=True, help_text='El articulo 310 es un regimen especial para las cesantias de los\n                                         empleados de la construccion, sin embargo existe una polemica sobre si esta vigente\n                                         o derogado tacitamente.\n                                         Indica si se calculará considerando este articulo o si se hara con el regimen general', verbose_name='Aplica el art. 310 CST?'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='aportes_cooperativas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor descontado por aportes en coopertivas', max_digits=14),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='aportes_fondo_empleados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor descontado por aportes al fondo de empleados', max_digits=14),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='avance_del_contrato',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Solo para los contratos de obra o labor, el avance de la obra\n                                              o de la labor especifica, en el momento del despido del trabajador', max_digits=5),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='bonificaciones_primer_semestre',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total pagado por concept de bonificaciones, comisiones o\n                                                         cualquiera que sea la denominacion que se de, durante el primer semestre', max_digits=14),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='bonificaciones_segundo_semestre',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total pagado por concept de bonificaciones, comisiones o\n                                                         cualquiera que sea la denominacion que se de, durante el segundo semestre.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='causal_terminacion',
            field=models.CharField(choices=[('sin', 'Despido Sin Justa Causa'), ('con', 'Despido Con Justa Causa'), ('ren', 'Renuncia Voluntaria')], default='con', help_text='Indica porque terminó el  contrato laboral', max_length=200, verbose_name='motivo terminacion del contrato'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='clase_contrato',
            field=models.CharField(choices=[('ind', 'Contrato Indefinido'), ('fij', 'Termino Fijo'), ('obr', 'Por Obra o Labor')], default='fij', help_text='Indica que tipo de contrato se está\n                                      liquidando', max_length=200, verbose_name='clase de contrato'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='cuota_descuento_libranza',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En caso que le descuenten una suma mensual se puede  indicar\n                                                   en este campo.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='demanda_salarios_caidos',
            field=models.BooleanField(default=False, help_text='Los salarios caidos es una indemnizacion moratoria,\n                                                  que se debe pagar cuando al finalizar el contrato no se liquidaron\n                                                  las prestaciones sociales.\n                                                  En este caso se pregunta si se ha realizado una demanda por este\n                                                  concepto antes de dos años de finalizado el contrato', verbose_name='salarios caidos antes de 2 años del despido?'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='dias_nomina',
            field=models.DecimalField(decimal_places=0, default=15, help_text='El numero de dias de nomina pendientes por pagar a la hora de liquidar', max_digits=14),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='dias_semanales',
            field=models.DecimalField(decimal_places=0, default=7, help_text='Solo para quienes trabajen por jornal.\n                                         Indica el numero de dias a la semana que se trabajaba.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='dias_suspencion_primer_semestre',
            field=models.IntegerField(default=0, help_text='El total de dias de suspencion del contrato durante\n                                                          el primer semestre. (las incapacidades NO cuentan como suspencion,\n                                                          se trata es de aquellos dias que se otorgó permiso o que se sanciono\n                                                          al trabajador)', verbose_name='dias de suspencion 1er Semestre'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='dias_suspencion_segundo_semestre',
            field=models.IntegerField(default=0, help_text='El total de dias de suspencion del contrato durante\n                                                           el segundo semestre. (las incapacidades NO cuentan como suspencion,\n                                                           se trata es de aquellos dias que se otorgó permiso o que se sanciono\n                                                           al trabajador)', verbose_name='dias de suspencion 2do Semestre'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='dias_vacaciones_disfrutados',
            field=models.IntegerField(default=0, help_text='El numero total de dias de vacaciones que ha disfrutado\n                                                      correspondientes al periodo laborado (no cuentan vacaciones de periodos\n                                                      anteriores)', verbose_name='dias de vacacion'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='empleado',
            field=models.CharField(blank=True, help_text='Nombre del empleado a liquidar las prestaciones sociales', max_length=200, verbose_name='nombre del empleado'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='empresa',
            field=models.CharField(blank=True, help_text='Razon social de la empresa que liquida (este campo es opcional)', max_length=200, verbose_name='empresa contratante'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='fecha_finalizacion',
            field=models.DateField(default=datetime.date(2017, 1, 31), help_text='Solo para contratos a termino fijo o por obra y labor:\n                                          Corresponde a la fecha que se acordo iba a finalizar el contrato '),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2016, 1, 31), help_text='Fecha en la cual inicio el contrato de trabajo que se pretende liquidar'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='fecha_liquidacion',
            field=models.DateField(default=datetime.date(2017, 1, 31), help_text='La fecha en la cual se liquida el contrato ya sea por despido,\n                                         por renuncia o simplemente por vencimiento'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='horas_extra_pendientes',
            field=models.FloatField(default=0, help_text='Para los salarios pendientes por pagar indica el pago pendiente\n                                               por concepto de horas extra.', max_length=15),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='horas_extra_primer_semestre',
            field=models.FloatField(default=0, help_text='Indica el dinero total en pesos, pagado por horas extra\n                                                     durante el primer semestre.', max_length=15),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='horas_extra_segundo_semestre',
            field=models.FloatField(default=0, help_text='Indica el dinero total en pesos, pagado por horas extra\n                                                      durante el segundo semestre.', max_length=15),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='porcentaje_descuento_prestamos',
            field=models.FloatField(default=0.0, help_text='Porcentaje de descuento que le hacen por concepto de\n                                                       libranza', max_length=6, verbose_name='porcentaje descuento libranza'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='salario_diario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En el caso de trabajadores que trabajan por jornal o medio tiempo,\n                                         indica el salario basico por un (1) dia de trabajo', max_digits=14),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='tipo_salario',
            field=models.CharField(choices=[('confianza', 'Empleado De Confianza (sin h. extras)'), ('normal', 'Salario Normal'), ('integral', 'Salario Integral (superior a 10 minimos)'), ('construccion', 'Construccion (por jornal durante una obra)'), ('domestico', 'Empleado Domestico (por jornal varios dias a la semana)')], default='normal', help_text='Indica si el salario tiene alguna condicion especial, como puede ser\n                                    pago por jornales, salario integral o salarios sin derecho a horas extras', max_length=30),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='ultimo_salario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hace referencia al ultimo salario basico que recibio el\n                                         trabajador por un (1) mes de trabajo.', max_digits=14),
        ),
    ]
