# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AportePension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_vigencia', models.DateField(default=django.utils.timezone.now)),
                ('final_vigencia', models.DateField(null=True)),
                ('porcentaje_aporte_empresa', models.FloatField(default=0.0, max_length=6, verbose_name='porcentaje aportado por empresa')),
                ('porcentaje_aporte_empleado', models.FloatField(default=0.0, max_length=6, verbose_name='porcentaje aportado por empleado')),
            ],
        ),
        migrations.CreateModel(
            name='AporteSalud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_vigencia', models.DateField(default=django.utils.timezone.now)),
                ('final_vigencia', models.DateField(null=True)),
                ('porcentaje_aporte_empresa', models.FloatField(default=0.0, max_length=6, verbose_name='porcentaje aportado por empresa')),
                ('porcentaje_aporte_empleado', models.FloatField(default=0.0, max_length=6, verbose_name='porcentaje aportado por empleado')),
            ],
        ),
        migrations.CreateModel(
            name='SalarioMinimo',
            fields=[
                ('vigencia_smmlv', models.IntegerField(default=2018, primary_key=True, serialize=False, verbose_name='año de vigencia')),
                ('smmlv', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='salario minimo vigente')),
                ('aux_trans', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='auxilio de transporte')),
            ],
        ),
    ]
