# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadValorTributario',
            fields=[
                ('vigencia_UVT', models.IntegerField(default=2018, primary_key=True, serialize=False, verbose_name='año de vigencia')),
                ('valor_UVT', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Unidad de valor tributario vigente')),
            ],
        ),
    ]
